### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by grunenwald** [nichuguen/SteamNetwork#1]

**Comment by grunenwald** [comment]
L'équipe Déruaz/Caraccio/Brandt avaient pris cette option y'a 2 ans, mais on n'avait pas été capable de la déployer chez moi (Vincent et moi)... Bon on n'a pas insisté longtemps et vous êtes ptet meilleurs que c't'équipe, mais pensez-y quand même, c'est ptet pas utile de trop compliquer... De mon côté si c'est déployé qq part, ça me suffit pour eval le projet

**Comment by ymaktepi** [comment]
Le but principal est de simplifier le "déploiement" chez tout le monde pour le developpement.  J'ai un serveur sur lequel je peux facilement déployer des containers, et l'objectif secondaire était de déployer dessus pour le rendu.

On verra si @thegazou et Arnaud arrivent facilement à déployer chez eux pour dev. Sinon, on fera autrement. Je vais completer le readme pour un déploiement sans docker.

**Comment by grunenwald** [comment]
Ok pour moi

**Comment by ymaktepi** [comment]
C'est résolu dans #2
